---
- name: generate a hosts file
  hosts: all
  tasks:
  - name: template a file to /etc/file.conf
    ansible.builtin.template
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
